name = "last-course-count"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-04-10"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[assets]
directory = "static"
binding = "ASSETS"
